### ISSUE TITLE
"Don't report bugs yet."

### ISSUE THREAD

**Issue by szepeviktor** [serversideup/docker-ansible#1]
@jaydrogers You can keep files under control

- shell scripts
- Dockerfiles
- YAML files
- GHA workflows
- Markdown files
- spelling everywhere
- IDE settings (EditorConfig)
- No byte should escape.

https://github.com/szepeviktor/byte-level-care/tree/master/.github/workflows 👀

But building a nuclear ☢️ power plant may not be to your liking.

**Comment by jaydrogers** [comment]
12+ hour day sitting at the computer trying to get this to work 🤪

I warned ya 😃

I'll circle back and clean it up 🤣

**Comment by szepeviktor** [comment]
All right.
