### ISSUE TITLE
Exceeding the speed of light

### ISSUE THREAD

**Issue by szepeviktor** [serversideup/docker-ansible#5]
### Steps To Reproduce

1. https://github.com/search?q=repo%3Aserversideup%2Fdocker-ansible%20lightwieght&type=code

### Outcome

No more typos! Use https://github.com/crate-ci/typos in your workflows.

### Affected Docker Images

none

**Comment by szepeviktor** [comment]
Please fix repo details too ⚙️

![image](https://github.com/user-attachments/assets/bc7af570-1410-4da8-9323-672eb880ba30)

**Comment by szepeviktor** [comment]
The hub too.

![image](https://github.com/user-attachments/assets/639ba752-6857-453f-989d-4bbf627768b0)

**Comment by jaydrogers** [comment]
Thanks @szepeviktor 😁

I always appreciate you helping me clean things up
